# Generated by Django 2.2.13 on 2020-06-16 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('apepaterno', models.CharField(blank=True, max_length=100)),
                ('apematerno', models.CharField(blank=True, max_length=100)),
                ('fechanacimiento', models.DateField()),
                ('curp', models.CharField(blank=True, max_length=18)),
                ('matricula', models.CharField(blank=True, max_length=10)),
                ('escuela_type', models.PositiveSmallIntegerField(choices=[(1, 'SINDICATO ALBA ROJA NUM. 20 02EES0212Q')])),
                ('tutor', models.CharField(max_length=40, null=None, verbose_name='Nombre Tutor:  ')),
                ('grado', models.IntegerField(default=1)),
                ('grupo', models.CharField(default='A', max_length=1)),
            ],
        ),
    ]
