# Generated by Django 2.2.13 on 2020-06-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200621_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fechanacimiento',
            field=models.DateTimeField(max_length=8),
        ),
    ]
